name: Deploy Vite Site to GitHub Pages (Main Branch)

on:
  push:
    branches:
      - main  # Triggers on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Choose the version compatible with your project

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to docs folder on main branch
        run: |
          rm -rf ./docs
          mv ./dist ./docs
        - name: Push changes to main branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Deploy to GitHub Pages"
          git push origin main
